plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solyan.iptv'
    compileSdk 35

    defaultConfig {
        applicationId 'com.solyan.iptv'
        minSdk 21
        targetSdk 28
        versionCode 4
        versionName '0.2.2'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.android.exoplayer:exoplayer-core:2.19.1'
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.19.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.19.1'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.19.1'
}
